branch-defaults:
  default:
    environment: Nfudacityudagram-env-3
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: Nf_UdacityUdagram
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
